---
- name: This play will install apache web servers on all the hosts
  hosts: all
  become: yes
  tasks:
    - name: Task1 will install nginx using apt
      apt:
        name: nginx
        update_cache: yes
        state: latest
